# Basic dependabot.yml file

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for a `nuget` in the `root` directory
    directory: "/"
    # Check for updates once a day
    schedule:
      interval: daily