name: New Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    uses: RicochetStudios/registry/.github/workflows/ci.yml@main
  create:
    name: Create release
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true